### ISSUE TITLE
ClouDNS.php Creates a Master not Secondary Zone

### ISSUE THREAD

**Issue by zwankie** [lambdatwelve/plesk-cloudns#1]
Hey Nick,

Thanks for the good job but for some reason the ClouDNS.php script creates a Master Zone when I use it in Plesk 17.8

I create the domain as usual then within seconds it is in cloudns.net but as a Master Zone.

What is required to bug-fix or change it to create a Slave/Secondary Zone

**Comment by hexblot** [comment]
That should not happen since type is hardcoded. 

Could you add the following

`error_log(print_r($params,1));`

in line 122 of the script ( should be a blank line after `$params = [..]` )

and then check if something is appended on `/var/log/sw-cp-server/error_log` when creating a zone?

**Comment by hexblot** [comment]
Please reopen if you can provide more info. Thanks.

**Comment by zwankie** [comment]
Apologies for the late reply Nick, I gave up on using ClouDNS directly with Plesk and rather do it manually from ClouDNS as required.
