### ISSUE TITLE
Add objectType 'site'

### ISSUE THREAD

**Issue by KrisLowet** [lambdatwelve/plesk-cloudns#4]
Hi

When _a customer_ adds a new domain, that DNS zone is managed by the objectType 'site'. I added this new _case_ to handle this:

```
      case 'site':
        switch($action) {
          case 'site_create':
            $this->addSlave($newValues['Domain Name']);
            break;
          case 'site_delete':
            $this->delSlave($oldValues['Domain Name']);
            break;
          default:
            // Do nothing, updates are handled by zone transfers.
        }
```

**Comment by hexblot** [comment]
Thank you @KrisLowet for the feedback and code, added to latest version!

**Comment by KrisLowet** [comment]
I think that there should be another case 'subdomain'. What do you think?
https://docs.plesk.com/en-US/obsidian/extensions-guide/plesk-features-available-for-extensions/subscribe-to-plesk-events/object-types-and-actions.49260/
